const PORT = 3300;

const express = require('express');
const app = express();
const cors = require('cors');


app.use(cors({ origin: '*', credentials: true, optionsSuccessStatus: 200 }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ limit: '1mb', extended: true }));




/*  return all data in a object generated by this line
 *    {status}  : 0 = success, any other number is an error
 *    {data}    : object
 *    {msg}     : message string
 */
resultResponse = (status, data, msg) => {
  /** standard end point response **/
  var result = {
    status : status,
    data : data, // json object,
    msg : msg
  }
  console.log(msg)
  return result;
}

// server hosted at localhost:3300
server = app.listen(PORT, () => {
  console.log("Listening on port " + PORT);
})

const chat = require('./endpoints/Chat.js')
app.use(chat)

// implements endpoints in Test.js
const test = require('./endpoints/Test.js');
app.use(test);


const path = require('path');
app.use(express.static(path.join(__dirname, 'build')))
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'build', 'index.html'))
})